repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-merge-conflict
      - id: fix-byte-order-marker
  - repo: https://github.com/godaddy/tartufo
    rev: v3.1.4
    hooks:
      - id: tartufo
        name: tartufo
        entry: tartufo
        args: [pre-commit]
        language: python
        language_version: python3.8
        pass_filenames: false
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: golangci-lint
      # TODO Uncomment in in a specific branch
      # - id: go-critic
      - id: go-build
      - id: go-mod-tidy
